### ISSUE TITLE
TableAid.ObjectComparerOne fails if there are no tablerows

### ISSUE THREAD

**Issue by celluj34** [ITAGroup/SpecAid#2]
Title.

Unless I can be convinced otherwise, I think it's a bug. I feel like ObjectComparerOne should take 0 or 1 rows, not exclusively 1 row.

**Comment by itauser** [comment]
Celluj34,
Thanks for the comment.  ObjectComparerOne by design only takes 1 row, as it intends to compare an object with a tablerow.  Consider the following:
• Object is not null, TableRow exists: compare properties.
• Object is null, TableRow exists: throw Assert.
• Object is not null, TableRow does not exist: throw Assert.
• Object is null, TableRow does not exist: should this be valid or throw Assert?
A cucumber example would be most helpful to determine expected behavior.
Regards
